-- 학교 택시 합승 매칭 앱용 Oracle SQL / PL/SQL 스키마
-- 그대로 SQL Developer 에서 파일 열기 후 실행하시면 됩니다
-- 반드시 SQL Developer의 "스크립트 실행(F5)"로 전체 실행하시면 됩니다
-- 주의: 아래 DROP 구문 때문에 같은 이름의 기존 테이블과 데이터는 삭제됩니다
-- 공용 DB나 기존 데이터가 있는 환경에서는 그대로 실행하지 말고 백업 후 사용하세요
-- 이 스크립트는 초기 스키마 생성용입니다
-- 이후 구조 변경은 ALTER TABLE 기반 마이그레이션 파일로 따로 관리하는 것을 권장합니다

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_users_set_updated_at'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_match_requests_set_active_flag'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE chat_room_members CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE chat_messages CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE chat_rooms CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE match_group_members CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE match_groups CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE match_requests CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE email_verifications CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE service_zones CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE universities CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE universities (
    university_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_name VARCHAR2(100) NOT NULL,
    school_email_domain VARCHAR2(100) NOT NULL UNIQUE,
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    boundary_radius_m NUMBER(10),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_universities_radius
        CHECK (boundary_radius_m IS NULL OR boundary_radius_m > 0)
);

CREATE TABLE app_users (
    user_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id NUMBER(19) NOT NULL,
    firebase_uid VARCHAR2(128) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    name VARCHAR2(50) NOT NULL,
    nickname VARCHAR2(50),
    phone VARCHAR2(20),
    is_email_verified NUMBER(1) DEFAULT 0 NOT NULL,
    account_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_app_users_university
        FOREIGN KEY (university_id) REFERENCES universities(university_id),
    CONSTRAINT uq_app_users_user_university
        UNIQUE (user_id, university_id),
    CONSTRAINT ck_app_users_email_verified
        CHECK (is_email_verified IN (0, 1)),
    CONSTRAINT ck_app_users_account_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE OR REPLACE TRIGGER trg_users_set_updated_at
BEFORE INSERT OR UPDATE ON app_users
FOR EACH ROW
BEGIN
    :NEW.email := LOWER(TRIM(:NEW.email));
    IF INSERTING THEN
        :NEW.created_at := NVL(:NEW.created_at, SYSTIMESTAMP);
    END IF;
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE email_verifications (
    verification_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    verification_code VARCHAR2(20) NOT NULL,
    purpose VARCHAR2(30) NOT NULL,
    is_verified NUMBER(1) DEFAULT 0 NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_email_verifications_user
        FOREIGN KEY (user_id) REFERENCES app_users(user_id),
    CONSTRAINT ck_email_verifications_verified
        CHECK (is_verified IN (0, 1)),
    CONSTRAINT ck_email_verifications_purpose
        CHECK (purpose IN ('SIGN_UP', 'SCHOOL_EMAIL', 'PASSWORD_RESET')),
    CONSTRAINT ck_email_verifications_email
        CHECK (email = LOWER(TRIM(email))),
    CONSTRAINT ck_email_verifications_verified_at
        CHECK (
            (is_verified = 0 AND verified_at IS NULL) OR
            (is_verified = 1 AND verified_at IS NOT NULL)
        )
);

CREATE INDEX idx_email_verifications_user_purpose
    ON email_verifications (user_id, purpose, is_verified);

CREATE TABLE service_zones (
    zone_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id NUMBER(19) NOT NULL,
    zone_name VARCHAR2(100) NOT NULL,
    zone_type VARCHAR2(20) NOT NULL,
    latitude NUMBER(10,7) NOT NULL,
    longitude NUMBER(10,7) NOT NULL,
    radius_m NUMBER(10) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_service_zones_university
        FOREIGN KEY (university_id) REFERENCES universities(university_id),
    CONSTRAINT uq_service_zones_name
        UNIQUE (university_id, zone_name),
    CONSTRAINT uq_service_zones_zone_university
        UNIQUE (zone_id, university_id),
    CONSTRAINT ck_service_zones_type
        CHECK (zone_type IN ('SCHOOL', 'STATION', 'CUSTOM')),
    CONSTRAINT ck_service_zones_active
        CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_service_zones_radius
        CHECK (radius_m > 0)
);

CREATE INDEX idx_service_zones_university
    ON service_zones (university_id);

CREATE TABLE match_requests (
    request_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    university_id NUMBER(19) NOT NULL,
    start_zone_id NUMBER(19) NOT NULL,
    target_zone_id NUMBER(19) NOT NULL,
    direction_type VARCHAR2(20) NOT NULL,
    request_status VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    desired_departure_at TIMESTAMP NOT NULL,
    max_wait_minutes NUMBER(3) DEFAULT 15 NOT NULL,
    requested_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expired_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    matched_at TIMESTAMP,
    active_request_flag NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_match_requests_user_university
        FOREIGN KEY (user_id, university_id) REFERENCES app_users(user_id, university_id),
    CONSTRAINT fk_match_requests_university
        FOREIGN KEY (university_id) REFERENCES universities(university_id),
    CONSTRAINT fk_match_requests_start_zone_university
        FOREIGN KEY (start_zone_id, university_id) REFERENCES service_zones(zone_id, university_id),
    CONSTRAINT fk_match_requests_target_zone_university
        FOREIGN KEY (target_zone_id, university_id) REFERENCES service_zones(zone_id, university_id),
    CONSTRAINT ck_match_requests_direction
        CHECK (direction_type IN ('SCHOOL_TO_STATION', 'STATION_TO_SCHOOL')),
    CONSTRAINT ck_match_requests_status
        CHECK (request_status IN ('WAITING', 'MATCHED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_match_requests_active_flag
        CHECK (active_request_flag IN (0, 1)),
    CONSTRAINT ck_match_requests_wait_minutes
        CHECK (max_wait_minutes BETWEEN 1 AND 120),
    CONSTRAINT ck_match_requests_zone_diff
        CHECK (start_zone_id <> target_zone_id),
    CONSTRAINT ck_match_requests_status_timestamps
        CHECK (
            (request_status = 'WAITING' AND matched_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL) OR
            (request_status = 'MATCHED' AND matched_at IS NOT NULL) OR
            (request_status = 'CANCELLED' AND cancelled_at IS NOT NULL) OR
            (request_status = 'EXPIRED' AND expired_at IS NOT NULL)
        )
);

CREATE OR REPLACE TRIGGER trg_match_requests_set_active_flag
BEFORE INSERT OR UPDATE OF request_status, matched_at, cancelled_at, expired_at, active_request_flag
ON match_requests
FOR EACH ROW
BEGIN
    IF :NEW.request_status = 'WAITING' THEN
        :NEW.active_request_flag := 1;
    ELSE
        :NEW.active_request_flag := 0;
    END IF;
END;
/

CREATE UNIQUE INDEX uq_match_requests_waiting_user
    ON match_requests (
        CASE WHEN active_request_flag = 1 THEN user_id END
    );

CREATE INDEX idx_match_requests_matching
    ON match_requests (
        university_id,
        start_zone_id,
        target_zone_id,
        direction_type,
        request_status,
        desired_departure_at
    );

CREATE TABLE match_groups (
    match_group_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id NUMBER(19) NOT NULL,
    start_zone_id NUMBER(19) NOT NULL,
    target_zone_id NUMBER(19) NOT NULL,
    direction_type VARCHAR2(20) NOT NULL,
    target_user_count NUMBER(2) DEFAULT 4 NOT NULL,
    matched_user_count NUMBER(2) DEFAULT 0 NOT NULL,
    match_status VARCHAR2(20) DEFAULT 'FORMING' NOT NULL,
    scheduled_departure_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    matched_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_match_groups_university
        FOREIGN KEY (university_id) REFERENCES universities(university_id),
    CONSTRAINT fk_match_groups_start_zone_university
        FOREIGN KEY (start_zone_id, university_id) REFERENCES service_zones(zone_id, university_id),
    CONSTRAINT fk_match_groups_target_zone_university
        FOREIGN KEY (target_zone_id, university_id) REFERENCES service_zones(zone_id, university_id),
    CONSTRAINT uq_match_groups_group_university
        UNIQUE (match_group_id, university_id),
    CONSTRAINT ck_match_groups_direction
        CHECK (direction_type IN ('SCHOOL_TO_STATION', 'STATION_TO_SCHOOL')),
    CONSTRAINT ck_match_groups_status
        CHECK (match_status IN ('FORMING', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_match_groups_target_count
        CHECK (target_user_count BETWEEN 2 AND 4),
    CONSTRAINT ck_match_groups_matched_count
        CHECK (matched_user_count BETWEEN 0 AND target_user_count),
    CONSTRAINT ck_match_groups_zone_diff
        CHECK (start_zone_id <> target_zone_id),
    CONSTRAINT ck_match_groups_status_timestamps
        CHECK (
            (match_status = 'FORMING' AND matched_at IS NULL AND cancelled_at IS NULL) OR
            (match_status = 'COMPLETED' AND matched_at IS NOT NULL) OR
            (match_status = 'CANCELLED' AND cancelled_at IS NOT NULL)
        )
);

CREATE INDEX idx_match_groups_lookup
    ON match_groups (
        university_id,
        start_zone_id,
        target_zone_id,
        direction_type,
        match_status,
        scheduled_departure_at
    );

CREATE TABLE match_group_members (
    match_group_member_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_group_id NUMBER(19) NOT NULL,
    university_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    request_id NUMBER(19) NOT NULL,
    member_role VARCHAR2(20) DEFAULT 'MEMBER' NOT NULL,
    join_status VARCHAR2(20) DEFAULT 'JOINED' NOT NULL,
    joined_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    left_at TIMESTAMP,
    CONSTRAINT fk_match_group_members_group
        FOREIGN KEY (match_group_id, university_id) REFERENCES match_groups(match_group_id, university_id),
    CONSTRAINT fk_match_group_members_user
        FOREIGN KEY (user_id, university_id) REFERENCES app_users(user_id, university_id),
    CONSTRAINT fk_match_group_members_request
        FOREIGN KEY (request_id) REFERENCES match_requests(request_id),
    CONSTRAINT uq_match_group_members_group_user
        UNIQUE (match_group_id, user_id),
    CONSTRAINT uq_match_group_members_request
        UNIQUE (request_id),
    CONSTRAINT ck_match_group_members_role
        CHECK (member_role IN ('LEADER', 'MEMBER')),
    CONSTRAINT ck_match_group_members_status
        CHECK (join_status IN ('JOINED', 'LEFT', 'REMOVED'))
);

CREATE INDEX idx_match_group_members_group
    ON match_group_members (match_group_id);

CREATE TABLE chat_rooms (
    chat_room_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_group_id NUMBER(19) NOT NULL UNIQUE,
    university_id NUMBER(19) NOT NULL,
    room_status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    CONSTRAINT fk_chat_rooms_group
        FOREIGN KEY (match_group_id, university_id) REFERENCES match_groups(match_group_id, university_id),
    CONSTRAINT uq_chat_rooms_room_university
        UNIQUE (chat_room_id, university_id),
    CONSTRAINT ck_chat_rooms_status
        CHECK (room_status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_chat_rooms_status_timestamps
        CHECK (
            (room_status = 'OPEN' AND closed_at IS NULL) OR
            (room_status = 'CLOSED' AND closed_at IS NOT NULL)
        )
);

CREATE TABLE chat_messages (
    message_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    university_id NUMBER(19) NOT NULL,
    sender_user_id NUMBER(19),
    message_type VARCHAR2(20) DEFAULT 'TEXT' NOT NULL,
    message_content VARCHAR2(2000),
    sent_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP,
    system_event_code VARCHAR2(30),
    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (chat_room_id, university_id) REFERENCES chat_rooms(chat_room_id, university_id),
    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_user_id, university_id) REFERENCES app_users(user_id, university_id),
    CONSTRAINT uq_chat_messages_message_room
        UNIQUE (message_id, chat_room_id),
    CONSTRAINT ck_chat_messages_type
        CHECK (message_type IN ('TEXT', 'IMAGE', 'SYSTEM')),
    CONSTRAINT ck_chat_messages_deleted
        CHECK (is_deleted IN (0, 1)),
    CONSTRAINT ck_chat_messages_sender
        CHECK (
            (message_type = 'SYSTEM' AND sender_user_id IS NULL) OR
            (message_type IN ('TEXT', 'IMAGE') AND sender_user_id IS NOT NULL)
        ),
    CONSTRAINT ck_chat_messages_payload
        CHECK (
            (message_type = 'SYSTEM' AND system_event_code IS NOT NULL AND message_content IS NOT NULL) OR
            (message_type IN ('TEXT', 'IMAGE') AND message_content IS NOT NULL AND system_event_code IS NULL)
        ),
    CONSTRAINT ck_chat_messages_deleted_at
        CHECK (
            (is_deleted = 0 AND deleted_at IS NULL) OR
            (is_deleted = 1 AND deleted_at IS NOT NULL)
        )
);

CREATE INDEX idx_chat_messages_room_time
    ON chat_messages (chat_room_id, sent_at);

CREATE TABLE chat_room_members (
    room_member_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    university_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    joined_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    left_at TIMESTAMP,
    last_read_message_id NUMBER(19),
    last_read_at TIMESTAMP,
    CONSTRAINT fk_chat_room_members_room
        FOREIGN KEY (chat_room_id, university_id) REFERENCES chat_rooms(chat_room_id, university_id),
    CONSTRAINT fk_chat_room_members_user
        FOREIGN KEY (user_id, university_id) REFERENCES app_users(user_id, university_id),
    CONSTRAINT fk_chat_room_members_last_read_message
        FOREIGN KEY (last_read_message_id, chat_room_id) REFERENCES chat_messages(message_id, chat_room_id),
    CONSTRAINT uq_chat_room_members
        UNIQUE (chat_room_id, user_id),
    CONSTRAINT ck_chat_room_members_read_pair
        CHECK (
            (last_read_message_id IS NULL AND last_read_at IS NULL) OR
            (last_read_message_id IS NOT NULL AND last_read_at IS NOT NULL)
        )
);

CREATE INDEX idx_chat_room_members_room
    ON chat_room_members (chat_room_id);

CREATE INDEX idx_app_users_university
    ON app_users (university_id);

COMMENT ON TABLE universities IS
    '학교 기본 정보 테이블입니다. 학교명, 학교 이메일 도메인, 위치 정보를 저장합니다.';

COMMENT ON TABLE app_users IS
    '앱 사용자 정보 테이블입니다. Firebase UID를 기준으로 사용자 계정을 식별합니다.';

COMMENT ON TABLE email_verifications IS
    '이메일 인증 이력 테이블입니다. 회원가입, 학교 이메일 인증, 비밀번호 재설정 용도로 사용합니다.';

COMMENT ON TABLE service_zones IS
    '학교와 지하철역 등 서비스 구역 정보를 저장합니다. 같은 학교 안에서 구역 이름은 중복될 수 없습니다.';

COMMENT ON TABLE match_requests IS
    '사용자가 생성한 합승 요청 테이블입니다. 함수 기반 유니크 인덱스로 사용자당 WAITING 요청은 1개만 허용됩니다.';

COMMENT ON TABLE match_groups IS
    '같은 학교, 같은 출발지/도착지, 같은 방향, 비슷한 시간대 요청이 모여 생성되는 매칭 그룹입니다.';

COMMENT ON TABLE match_group_members IS
    '매칭 그룹에 포함된 사용자 목록입니다. 각 요청은 하나의 그룹에만 속할 수 있습니다.';

COMMENT ON TABLE chat_rooms IS
    '매칭 그룹이 확정되면 생성되는 채팅방입니다. 한 매칭 그룹에는 하나의 채팅방만 생성됩니다.';

COMMENT ON TABLE chat_messages IS
    '채팅 메시지 테이블입니다. 일반 메시지와 시스템 메시지를 함께 저장합니다.';

COMMENT ON TABLE chat_room_members IS
    '채팅방 참여자 정보 테이블입니다. 마지막으로 읽은 메시지와 읽은 시각을 함께 관리합니다.';
