spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    username: ${DB_USERNAME:TAXI_DB}
    password: ${DB_PASSWORD:1234}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}